export interface EventData {
  id: string;
  title: string;
  organizer: string;
  organizerLogo: string;
  img: string;
  category: string;
  city: string;
  cityLabel: string;
  location: string;
  date: string;
  time: string;
  price: string;
  numericPrice: number;
  isHot?: boolean;
  description: string;
  terms: string[];
  facilities: { icon: string; label: string }[];
  socialMedia: { platform: string; url: string }[];
}

export const ALL_EVENTS: EventData[] = [
  {
    id: "ev-1",
    title: "Hillsong Worship Nights Asia Tour 2026",
    organizer: "Live Nation Asia",
    organizerLogo: "/logo/tix_logo.png?v=3",
    img: "/image_concer/banner_concer_1.png",
    category: "Music Concert",
    city: "jabodetabek",
    cityLabel: "Jabodetabek",
    location: "GBK Basketball Hall, Jakarta",
    date: "11 Sep 2026",
    time: "19:00 - 22:00",
    price: "Rp 850.000",
    numericPrice: 850000,
    isHot: true,
    description: "Experience an unforgettable night of worship with Hillsong Worship as they bring their Asia Tour 2026 to Jakarta. Join thousands of worshippers for a night filled with powerful music, incredible performances, and an atmosphere unlike any other. This is a night you will not want to miss.",
    terms: [
      "Tickets purchased are non-refundable and non-transferable.",
      "One ticket is valid for one person only.",
      "Maximum ticket purchase is 4 tickets per transaction.",
      "Attendees under 12 years of age are not permitted to enter the venue.",
      "Management reserves the right to refuse entry without refund.",
      "Recording devices and professional cameras are not permitted.",
      "The organizer is not responsible for lost or stolen items.",
      "Please arrive at least 30 minutes before the event starts.",
    ],
    facilities: [
      { icon: "fastfood", label: "Food Court" },
      { icon: "medical_services", label: "Medis" },
      { icon: "shopping_bag", label: "Merchandise" },
      { icon: "wc", label: "Mushola" },
      { icon: "local_parking", label: "Area Parkir" },
      { icon: "confirmation_number", label: "Tiket" },
    ],
    socialMedia: [
      { platform: "Instagram", url: "#" },
      { platform: "TikTok", url: "#" },
    ],
  },
  {
    id: "ev-2",
    title: "Pestapora Makassar 2026",
    organizer: "Boss Creator",
    organizerLogo: "/logo/tix_logo.png?v=3",
    img: "/image_concer/banner_concer_1.png",
    category: "Festival",
    city: "indonesia_timur",
    cityLabel: "Eastern Indonesia",
    location: "Celebes Convention Center, Makassar",
    date: "26 Jul 2026",
    time: "15:00 - 23:00",
    price: "Rp 225.000",
    numericPrice: 225000,
    isHot: true,
    description: "Pestapora Makassar 2026 hadir kembali dengan lineup artis terbaik dari seluruh Indonesia. Festival musik terbesar di kawasan timur Indonesia ini menghadirkan pengalaman tak terlupakan di Celebes Convention Center.",
    terms: [
      "Tiket tidak dapat dikembalikan atau ditukar.",
      "Satu tiket berlaku untuk satu orang.",
      "Dilarang membawa makanan dan minuman dari luar.",
      "Penyelenggara berhak menolak masuk tanpa pengembalian dana.",
    ],
    facilities: [
      { icon: "fastfood", label: "Food Court" },
      { icon: "medical_services", label: "Medis" },
      { icon: "shopping_bag", label: "Merchandise" },
      { icon: "local_parking", label: "Area Parkir" },
    ],
    socialMedia: [
      { platform: "Instagram", url: "#" },
    ],
  },
  {
    id: "ev-3",
    title: "VIXTAPE KONEKT Showcase Band",
    organizer: "VINDES Media",
    organizerLogo: "/logo/tix_logo.png?v=3",
    img: "/image_concer/banner_concer_1.png",
    category: "Indie & Alternative",
    city: "jabodetabek",
    cityLabel: "Jabodetabek",
    location: "Bengkel Space SCBD, Jakarta",
    date: "25–26 Jul 2026",
    time: "18:00 - 22:00",
    price: "Rp 125.000",
    numericPrice: 125000,
    isHot: false,
    description: "VIXTAPE KONEKT Showcase hadir menampilkan band-band indie terbaik pilihan VINDES Media. Dua malam penuh musik segar dan penampilan memukau di venue premium kawasan SCBD Jakarta.",
    terms: [
      "Tiket tidak dapat dikembalikan.",
      "Satu tiket berlaku untuk satu malam.",
      "Dilarang membawa minuman beralkohol.",
    ],
    facilities: [
      { icon: "fastfood", label: "Food Court" },
      { icon: "medical_services", label: "Medis" },
      { icon: "confirmation_number", label: "Tiket" },
    ],
    socialMedia: [
      { platform: "Instagram", url: "#" },
      { platform: "TikTok", url: "#" },
    ],
  },
  {
    id: "ev-4",
    title: "Joyland Sessions 2026 Bali",
    organizer: "Plainsong Live",
    organizerLogo: "/logo/tix_logo.png?v=3",
    img: "/image_concer/banner_concer_1.png",
    category: "Festival",
    city: "bali",
    cityLabel: "Bali",
    location: "Peninsula Island Nusa Dua, Bali",
    date: "14–16 Nov 2026",
    time: "14:00 - 23:00",
    price: "Rp 588.000",
    numericPrice: 588000,
    isHot: true,
    description: "Joyland Sessions 2026 returns to the stunning Peninsula Island in Nusa Dua, Bali. Three days of world-class music, art installations, and an unparalleled tropical festival experience.",
    terms: [
      "Tickets are non-refundable.",
      "All ages welcome with parental guidance for under 17.",
      "No outside food or beverages allowed.",
      "The organizer reserves the right to change lineup without notice.",
    ],
    facilities: [
      { icon: "fastfood", label: "Food Court" },
      { icon: "medical_services", label: "Medis" },
      { icon: "shopping_bag", label: "Merchandise" },
      { icon: "local_parking", label: "Area Parkir" },
      { icon: "wc", label: "Mushola" },
    ],
    socialMedia: [
      { platform: "Instagram", url: "#" },
    ],
  },
  {
    id: "ev-5",
    title: "Soundrenaline 2026 Jakarta",
    organizer: "Ravel Entertainment",
    organizerLogo: "/logo/tix_logo.png?v=3",
    img: "/image_concer/banner_concer_1.png",
    category: "Festival",
    city: "jabodetabek",
    cityLabel: "Jabodetabek",
    location: "Ancol Circuit Carnival, Jakarta",
    date: "15 Dec 2026",
    time: "15:00 - 23:00",
    price: "Rp 450.000",
    numericPrice: 450000,
    isHot: true,
    description: "Soundrenaline 2026 kembali hadir di Jakarta dengan lineup artis rock dan pop terbesar. Rasakan adrenalin di Ancol Circuit Carnival bersama ribuan penonton dari seluruh Indonesia.",
    terms: [
      "Tiket tidak dapat dikembalikan atau ditukar.",
      "Satu tiket berlaku untuk satu orang.",
      "Dilarang membawa senjata tajam atau benda berbahaya.",
      "Penyelenggara berhak menolak masuk tanpa pengembalian dana.",
    ],
    facilities: [
      { icon: "fastfood", label: "Food Court" },
      { icon: "medical_services", label: "Medis" },
      { icon: "shopping_bag", label: "Merchandise" },
      { icon: "local_parking", label: "Area Parkir" },
      { icon: "confirmation_number", label: "Tiket" },
    ],
    socialMedia: [
      { platform: "Instagram", url: "#" },
      { platform: "TikTok", url: "#" },
    ],
  },
  {
    id: "ev-6",
    title: "Bandung Indie Nation Fest 2026",
    organizer: "Kreatif Bandung",
    organizerLogo: "/logo/tix_logo.png?v=3",
    img: "/image_concer/banner_concer_1.png",
    category: "Indie & Alternative",
    city: "jawa_barat",
    cityLabel: "West Java",
    location: "Gedung Sate Open Park, Bandung",
    date: "15 Aug 2026",
    time: "15:00 - 22:00",
    price: "Rp 180.000",
    numericPrice: 180000,
    isHot: false,
    description: "Festival indie terbesar di Bandung hadir kembali menampilkan musisi-musisi terbaik dari scene indie lokal dan nasional di salah satu venue ikonik Kota Kembang.",
    terms: [
      "Tiket tidak dapat dikembalikan.",
      "Dilarang membawa minuman beralkohol.",
      "Satu tiket berlaku untuk satu orang.",
    ],
    facilities: [
      { icon: "fastfood", label: "Food Court" },
      { icon: "medical_services", label: "Medis" },
      { icon: "local_parking", label: "Area Parkir" },
    ],
    socialMedia: [{ platform: "Instagram", url: "#" }],
  },
  {
    id: "ev-7",
    title: "Jogja Jazz & Heritage Night",
    organizer: "Jogja Cultural Fest",
    organizerLogo: "/logo/tix_logo.png?v=3",
    img: "/image_concer/banner_concer_1.png",
    category: "Arts & Culture",
    city: "jawa_tengah",
    cityLabel: "Central Java & DIY",
    location: "Candi Prambanan, Yogyakarta",
    date: "28 Aug 2026",
    time: "19:30 - 23:00",
    price: "Rp 320.000",
    numericPrice: 320000,
    isHot: false,
    description: "Nikmati malam jazz yang magis di latar belakang kemegahan Candi Prambanan. Jogja Jazz & Heritage Night menghadirkan musisi jazz terbaik dalam suasana budaya yang tak tertandingi.",
    terms: [
      "Tiket tidak dapat dikembalikan.",
      "Dilarang mengambil foto komersial tanpa izin.",
      "Pakaian sopan diwajibkan.",
    ],
    facilities: [
      { icon: "fastfood", label: "Food Court" },
      { icon: "medical_services", label: "Medis" },
      { icon: "local_parking", label: "Area Parkir" },
    ],
    socialMedia: [{ platform: "Instagram", url: "#" }],
  },
  {
    id: "ev-8",
    title: "Surabaya Pop Sound Wave",
    organizer: "Surabaya Event Org",
    organizerLogo: "/logo/tix_logo.png?v=3",
    img: "/image_concer/banner_concer_1.png",
    category: "Pop & Rock",
    city: "jawa_timur",
    cityLabel: "East Java",
    location: "Grand City Exhibition Hall, Surabaya",
    date: "05 Sep 2026",
    time: "18:00 - 22:00",
    price: "Rp 210.000",
    numericPrice: 210000,
    isHot: false,
    description: "Surabaya Pop Sound Wave menghadirkan deretan artis pop terbaik di panggung megah Grand City. Rayakan musik pop Indonesia bersama ribuan penonton di Kota Pahlawan.",
    terms: [
      "Tiket tidak dapat dikembalikan.",
      "Satu tiket berlaku untuk satu orang.",
    ],
    facilities: [
      { icon: "fastfood", label: "Food Court" },
      { icon: "medical_services", label: "Medis" },
      { icon: "local_parking", label: "Area Parkir" },
      { icon: "confirmation_number", label: "Tiket" },
    ],
    socialMedia: [{ platform: "Instagram", url: "#" }],
  },
  {
    id: "ev-9",
    title: "Sumatera Rockfest Palembang",
    organizer: "Palembang Music Fest",
    organizerLogo: "/logo/tix_logo.png?v=3",
    img: "/image_concer/banner_concer_1.png",
    category: "Pop & Rock",
    city: "sumatera",
    cityLabel: "Sumatera",
    location: "PTC Open Stage, Palembang",
    date: "19 Sep 2026",
    time: "17:00 - 22:00",
    price: "Rp 195.000",
    numericPrice: 195000,
    isHot: false,
    description: "Rockfest terbesar di Sumatera hadir di Palembang! Nikmati penampilan band-band rock terbaik dari seluruh penjuru Sumatera di PTC Open Stage.",
    terms: [
      "Tiket tidak dapat dikembalikan.",
      "Dilarang membawa senjata tajam.",
      "Satu tiket berlaku untuk satu orang.",
    ],
    facilities: [
      { icon: "fastfood", label: "Food Court" },
      { icon: "medical_services", label: "Medis" },
      { icon: "local_parking", label: "Area Parkir" },
    ],
    socialMedia: [{ platform: "Instagram", url: "#" }],
  },
  {
    id: "ev-10",
    title: "Borneo Music Tour Balikpapan",
    organizer: "Borneo Live Event",
    organizerLogo: "/logo/tix_logo.png?v=3",
    img: "/image_concer/banner_concer_1.png",
    category: "Music Concert",
    city: "kalimantan",
    cityLabel: "Kalimantan",
    location: "BSCC Dome Balikpapan",
    date: "03 Oct 2026",
    time: "19:00 - 22:00",
    price: "Rp 260.000",
    numericPrice: 260000,
    isHot: false,
    description: "Borneo Music Tour hadir di Balikpapan membawa artis-artis nasional ke jantung Kalimantan. Saksikan penampilan spektakuler di BSCC Dome yang megah.",
    terms: [
      "Tiket tidak dapat dikembalikan.",
      "Satu tiket berlaku untuk satu orang.",
      "Dilarang membawa makanan dan minuman dari luar.",
    ],
    facilities: [
      { icon: "fastfood", label: "Food Court" },
      { icon: "medical_services", label: "Medis" },
      { icon: "local_parking", label: "Area Parkir" },
      { icon: "confirmation_number", label: "Tiket" },
    ],
    socialMedia: [{ platform: "Instagram", url: "#" }],
  },
  {
    id: "ev-11",
    title: "Ancol Summer Beach Party",
    organizer: "Tix Experience",
    organizerLogo: "/logo/tix_logo.png?v=3",
    img: "/image_concer/banner_concer_1.png",
    category: "Festival",
    city: "jabodetabek",
    cityLabel: "Jabodetabek",
    location: "Symphony of the Sea, Ancol, Jakarta",
    date: "22 Aug 2026",
    time: "15:00 - 23:00",
    price: "Rp 175.000",
    numericPrice: 175000,
    isHot: true,
    description: "Party di tepi pantai Ancol bersama DJ dan artis terbaik. Ancol Summer Beach Party menghadirkan suasana festival pantai yang meriah dengan musik, makanan, dan pemandangan laut yang indah.",
    terms: [
      "Tiket tidak dapat dikembalikan.",
      "Dilarang membawa minuman beralkohol.",
      "Anak di bawah 12 tahun harus didampingi orang tua.",
    ],
    facilities: [
      { icon: "fastfood", label: "Food Court" },
      { icon: "medical_services", label: "Medis" },
      { icon: "shopping_bag", label: "Merchandise" },
      { icon: "local_parking", label: "Area Parkir" },
    ],
    socialMedia: [
      { platform: "Instagram", url: "#" },
      { platform: "TikTok", url: "#" },
    ],
  },
  {
    id: "ev-12",
    title: "Malang Music Camp 2026",
    organizer: "Malang Creative",
    organizerLogo: "/logo/tix_logo.png?v=3",
    img: "/image_concer/banner_concer_1.png",
    category: "Indie & Alternative",
    city: "jawa_timur",
    cityLabel: "East Java",
    location: "Coban Rondo Outdoor Arena, Malang",
    date: "10 Oct 2026",
    time: "14:00 - 22:00",
    price: "Rp 150.000",
    numericPrice: 150000,
    isHot: false,
    description: "Malang Music Camp mengajak kamu menikmati musik indie di alam terbuka Coban Rondo yang sejuk dan hijau. Pengalaman festival yang berbeda dari biasanya.",
    terms: [
      "Tiket tidak dapat dikembalikan.",
      "Pakaian hangat disarankan.",
      "Satu tiket berlaku untuk satu orang.",
    ],
    facilities: [
      { icon: "fastfood", label: "Food Court" },
      { icon: "medical_services", label: "Medis" },
      { icon: "local_parking", label: "Area Parkir" },
    ],
    socialMedia: [{ platform: "Instagram", url: "#" }],
  },
];
