[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/api/api/v1/:splat"
  status = 200
  force = true
